### ISSUE TITLE
[Feature] User Sign in using the fake data

### ISSUE THREAD

**Issue by clevetong** [ANU-Student-Connect/student-connect-2024S2#31]
When the user inputs the email address and password in the fake data, the home page of the app will show.
Criteria:
- When the user input any email address and password in the fake data, the home page will always show.
- Possibly set cookie to remember user's sign in status.

**Comment by ahmadMusawi** [comment]
- The code extracts the email and password from the POST request and then checks if both fields are provided and not blank otherwise if either the email or password or both are not provided it will have the server response with the status "Bad Request" (code 400).
- It also sets a cookie "user" with the email address which can remember the status of the user when login.

**Comment by CloudyRowly** [comment]
Open a pull request.

**Comment by ahmadMusawi** [comment]
Pull request created
